//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssetManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int AssetId { get; set; }
        public string Manufacturer { get; set; }
        public string AssetDescription { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
