//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssetManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desposal
    {
        public Desposal()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int DesposalId { get; set; }
        public int StockId { get; set; }
        public System.DateTime DesposalDate { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
