//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssetManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.AssetAssigns = new HashSet<AssetAssign>();
        }
    
        public int StockId { get; set; }
        public byte[] AssetCode { get; set; }
        public int AssetId { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Barcode { get; set; }
        public int Price { get; set; }
        public System.DateTime AcquiredDate { get; set; }
        public int VendorId { get; set; }
        public int Warranty { get; set; }
        public string Status { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> UserAssignDate { get; set; }
        public Nullable<int> MaintenanceId { get; set; }
        public Nullable<int> DesposalId { get; set; }
    
        public virtual ICollection<AssetAssign> AssetAssigns { get; set; }
        public virtual Asset Asset { get; set; }
        public virtual Desposal Desposal { get; set; }
        public virtual Maintenance Maintenance { get; set; }
        public virtual User User { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
